---
ci:
    autofix_prs: true
    autoupdate_schedule: monthly

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
          - id: check-symlinks
          - id: check-yaml
          - id: check-json
          - id: destroyed-symlinks
          - id: end-of-file-fixer
          - id: requirements-txt-fixer
            name: Fix requirements*.txt
            files: ^requirements.*\.txt$
          - id: trailing-whitespace

    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.3
      hooks:
          - id: yamlfmt
            args: [--width, '100']

    - repo: https://github.com/adrienverge/yamllint.git
      rev: v1.37.0 # or higher tag
      hooks:
          - id: yamllint
            args: [--format, parsable, --strict, -d, '{line-length: {max: 100}}']

    - repo: local
      hooks:
          - id: replace-yml-with-yaml
            name: Federation entries must be .yaml, not .yml
            entry: Federation entries must be .yaml, not .yml
            files: ^src/instances/.*(?<!\.yaml)$
            language: fail
