---
name: Build container
on:
    pull_request:
    push:
        branches:
            - main

jobs:
    build_publish_container_image:
        name: Build container and optionally publish on GH Container Registry
        if: github.repository_owner == 'datalab-org'
        runs-on: ubuntu-latest

        environment:
            name: container-image
            url: https://github.com/${{ github.repository }}/pkgs/container/${{ vars.IMAGE_NAME }}

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                  push: ${{ github.event_name == 'push' }}
                  tags: |
                      ghcr.io/{{ github.repository_owner }}/{{ github.repository }}:latest
                      ghcr.io/{{ github.repository_owner }}/{{ github.repository }}:${{ github.sha }}
