---
name: Build container
on:
    pull_request:
    push:
        branches:
            - main

jobs:
    build_container_image:
        name: Build container
        if: github.repository_owner == 'datalab-org'
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                  push: false
                  cache-to: type=gha,scope=build
                  cache-from: type=gha,scope=build,mode=max

    publish_container_image:
        name: Publish container on ghcr.io
        if: github.repository_owner == 'datalab-org' && github.event_name == 'push'
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Extract metadata (tags, labels) for Docker
              id: docker-metadata
              uses: docker/metadata-action@v5
              with:
                  images: ${{ github.repository }}
                  tags: |
                      type=sha,latest=true

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                  context: .
                  push: true
                  provenance: false
                  cache-from: type=gha,scope=build,mode=max
                  tags: ${{ steps.docker-metadata.outputs.tags }}
                  labels: ${{ steps.docker-metadata.outputs.labels }}
