---
name: Validate entries
on:
    pull_request:

    push:
        branches:
            - main

jobs:
    validate:
        name: Lint & validate
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up Python 3.12
              uses: actions/setup-python@v5
              with:
                  python-version: '3.12'

            - name: Set up cached uv
              uses: hynek/setup-cached-uv@v2

            - name: Install dependencies
              run: |
                  uv venv
                  uv pip install -r requirements.txt

            - name: Run pre-commit
              run: |
                  source .venv/bin/activate
                  pre-commit run --all-files --show-diff-on-failure

            - name: Validate entries against LinkML schema
              run: |
                  source .venv/bin/activate
                  make all
